name = "project_roadwork/light_reflector"
version = "1.0.0-infdev.3"
description = "A vehicle-based light reflector that reflects decals and basepart reflectors at long distances on a road."
authors = ["Illinois_Roadbuff (Rogue Jr)"]
repository = "https://codeberg.org/project-roadwork/light-reflector.git"
license = "MPL-2.0"
includes = ["pesde.toml","README.md","LICENSE","NOTICE","src/**/*.luau"]

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]
