[package]
name = "illinois-roadbuff/light-reflector"
version = "0.0.1"
description = "A vehicle-based light reflector that reflects decals and basepart reflectors at long distances on a road."
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "Apache-2.0"
includes = ["pesde.toml","README.md","LICENSE","NOTICE","src/**/*.luau"]
repository = "https://codeberg.org/project-roadwork/light-reflector.git"
authors = ["Illinois_Roadbuff (Rogue Jr) <illinois_roadbuff@proton.me>"]
